# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

tasks:
  setup:
    summary: Sets up Taskfile auto-completion
    desc: |
      This task performs the following steps to set up auto-completion for Taskfile:
      1. Downloads the bash auto-completion script for Taskfile.
      2. Adds the current user to the sudoers file to allow moving the script without a password.
      3. Moves the downloaded script to the bash-completion directory.
      4. Adds a line to the .bashrc file to source the auto-completion script on shell startup.
    cmds:
      - curl -LO https://raw.githubusercontent.com/go-task/task/main/completion/bash/task.bash
      - 'echo "{{.USER}} ALL=(ALL:ALL) NOPASSWD: /usr/bin/mv" | sudo tee /etc/sudoers.d/{{.USER}}'
      - sudo mv task.bash /usr/share/bash-completion/completions/
      - echo 'source /usr/share/bash-completion/completions/task' >> ~/.bashrc

  install-poetry:
    summary: Installs Poetry package manager
    desc: |
      This task performs the following steps to install Poetry package manager:
      1. Downloads the installation script for Poetry.
      2. Executes the installation script.
    cmds:
      - pip install poetry
      - poetry install
      - pip install --upgrade poetry
      - poetry update

  install-trivy:
    summary: Installs Trivy vulnerability scanner
    desc: |
      This task performs the following steps to install Trivy vulnerability scanner:
      1. Installs necessary packages (wget, apt-transport-https, gnupg).
      2. Downloads and stores the public key for the Trivy repository.
      3. Adds the Trivy repository to the APT sources list.
      4. Updates the list of available packages.
      5. Installs Trivy.
    cmds:
      - sudo apt-get install wget apt-transport-https gnupg
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
      - echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
      - sudo apt-get update
      - sudo apt-get install trivy